import type { Metadata } from 'next';
import { Inter as FontSans } from 'next/font/google';

import Footer from '@/components/Footer/footer';
import { NavBar } from '@/components/NavBar';
import { ThemeProvider } from '@/components/ThemeProvider';
import { Separator } from '@/components/ui/separator';
import { cn } from '@/lib/utils';

import './globals.css';

export const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased',
          fontSans.variable
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <NavBar />

          {children}
          <Separator />
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
